### PR TITLE
Combine common settings into a config block

### PR DESCRIPTION
**Pull request by zingo**
Common setting like compiler settings and target HW are bunched into one setting that reflect all tasks
Also some slight fixes was done to make all task build

### CODE REVIEW

**Comment by zingo** [comment]
Wow I was able to just click in VS code to create a PULL request :)
Here is nothing that important at all. I just playing with the TARGET define so I only need to change it in one place :)

**Comment by zingo** [comment]
Added some initial touchscreen code the set speed/incline as test for debug, instead of using the buttons as they don't exist on my other target.

**Comment by lefty01** [comment]
I'm always good with some kind of clean-up, thx.

right now I personally do not really like how the code looks ... it's not very pretty ;)
my first experience with the platformio setup was after forking: https://github.com/lefty01/esp32-morphing-clock
that code had some neat structure ... so I think we could even further  modularize certain pieces.

**Comment by zingo** [comment]
Doing little now and then help a lot :)

**Pull request merged**
